### ISSUE TITLE
help with compiling 

### ISSUE THREAD

**Issue by PSYCHOVICH229** [riconuts/troll-engine#10]
### Describe your bug here.

help 

### Command Prompt/Terminal logs (if existing)

```bash
troll-engine-main>haxelib run lime build windows
source/flixel/FlxObject.hx:8: characters 8-27 : Type not found : flixel.path.FlxPath
source/flixel/FlxObject.hx:783: characters 32-39 : Type not found : FlxPath
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by nebulazorua** [comment]
Make sure you're on HaxeFlixel 5.2.0

**Comment by PSYCHOVICH229** [comment]
now i have this 
C:\Users\HEH\Downloads\troll-engine-main>lime build windows
source/hxcodec/VideoHandler.hx:8: characters 8-29 : Type not found : hxcodec.vlc.VLCBitmap
source/hxcodec/VideoHandler.hx:14: characters 28-37 : Type not found : VLCBitmap
source/Main.hx:24: lines 24-231 : ... Defined in this class
source/Main.hx:27: characters 33-61 : Warning : Cannot execute 'git config --get remote.origin.url'
source/hxcodec/VideoHandler.hx:14: characters 28-37 : Type not found : VLCBitmap
source/PlayState.hx:150: lines 150-4960 : ... Defined in this class
source/hxcodec/VideoHandler.hx:14: characters 28-37 : Type not found : VLCBitmap
source/VideoPlayerState.hx:8: lines 8-47 : ... Defined in this class
source/VideoPlayerState.hx:33: characters 15-29 : hxcodec.VideoHandler has no field finishCallback
source/VideoPlayerState.hx:34: characters 9-18 : hxcodec.VideoHandler has no field playVideo
source/VideoPlayerState.hx:40: characters 19-23 : hxcodec.VideoHandler has no field stop
source/VideoPlayerState.hx:41: characters 19-26 : hxcodec.VideoHandler has no field dispose

**Comment by riconuts** [comment]
You need hxCodec too

**Comment by PSYCHOVICH229** [comment]
> You need hxCodec too

But i have it
![image](https://github.com/riconuts/troll-engine/assets/130473579/ad212706-cc30-47ef-8bb0-d0466fc5da93)

**Comment by PSYCHOVICH229** [comment]
> You need hxCodec too

Ok i updated it now it works thx for help
