### ISSUE TITLE
compiling error :(((

### ISSUE THREAD

**Issue by Rice1367** [riconuts/troll-engine#16]
### Describe your problem here.

I tried to compile the engine, but it didn't work:

- source/flixel/addons/transition/FlxTransitionableState.hx:67: lines 67-77 : Warning : switchTo is deprecated, use startOutro
source/scripts/FunkinHScript.hx:570: lines 570-586 : Warning : switchTo is deprecated, use startOutro
source/Main.hx:29: characters 33-61 : Warning : Cannot execute 'git config --get remote.origin.url'
source/PlayState.hx:1423: characters 26-29 : Warning : Local variable snd might be used before being initialized
Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/2,5,1/hxcodec/vlc/LibVLCBuild.xml"

My version of Haxe is 4.2.5 and this is my list of libraries:
actuate: [1.9.0]
box2d: [1.2.3]
discord_rpc: [git]
faxe: [git]
flixel-addons: 2.11.0 3.1.1 [3.2.1] git
flixel-demos: [3.0.0]
flixel-templates: [2.6.6]
flixel-tools: [1.5.1]
flixel-ui: [2.5.0]
flixel: 4.11.0 5.3.1 [5.4.1]
hmm: [3.1.0]
hscript: [2.5.0]
hxCodec: [2.5.1]
hxcpp-debug-server: [1.2.4]
hxcpp: [4.3.2]
hxvm-luajit: [git]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: [8.0.2]
linc_luajit: [git]
newgrounds: [2.0.2]
openfl-samples: [8.7.0]
openfl: [9.2.2] git
polymod: [git]
systools: [1.1.0]
thx.core: [0.44.0]
thx.semver: [0.2.2]
utest: [1.13.2]

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Rice1367** [comment]
ye
now i can compile it, I just needed to reinstall hxCodec (2.5.1). I don't know if it also affected the fact that I reinstalled it with the cmd path in the engine folder. But now when I try to enter the Chart editor this happens before crashing

![image](https://github.com/riconuts/troll-engine/assets/143020225/5a52206e-1711-4f17-ba2a-7c3d7646dbea)

**Comment by riconuts** [comment]
that may be an issue with whatever song you're opening on the chart editor
