### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by LuckierCatt** [riconuts/troll-engine#17]
### Describe your problem here.

Trying to compile but keep getting this error

troll-engine-main/troll-engine-main/.haxelib/openfl/git/src/openfl/utils/_internal/ShaderMacro.hx:426: characters 32-43 : Unknown identifier : __glVersion

here's a list of the libraries I have installed and versions

- discord_rpc: [git]
- flixel-addons: [3.0.2] 3.1.1 3.2.1
- flixel-tools: [1.5.1]
- flixel-ui: [2.5.0]
- flixel: [5.2.2] 5.3.1 5.4.1
- hmm: [3.1.0]
- hscript: [2.5.0]
- hxCodec: 2.5.1 2.6.1 3.0.0 [3.0.2] git
- hxcpp-debug-server: [1.2.4]
- hxcpp: [4.3.2]
- lime: [8.0.1] 8.1.0
- linc_luajit: [git]
- openfl: 9.2.1 [git]
- SScript: [6.1.80] 6.1.800
- thx.core: [0.44.0]
- tjson: [1.4.0]
- utest: [1.13.2]

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by riconuts** [comment]
Update openfl maybe... If that doesn't solve it then here's the full list of libraries that I have while compiling:

discord_rpc: [git]
flixel-addons: [3.0.2]
flixel-tools: [1.5.1]
flixel-ui: [2.5.0]
flixel: [5.3.1]
hmm: [3.1.0]
hscript: [2.5.0]
hxCodec: [2.6.1]
hxcpp-debug-server: [1.2.4]       
hxcpp: [4.3.2]
lime: [8.0.2]
linc_luajit: [git]
openfl: [9.2.2]

**Comment by LuckierCatt** [comment]
looks like that fixed it but now im getting this:

source/VideoPlayerState.hx:42: characters 10-24 : hxcodec.flixel._FlxVideo.VideoHandler has no field finishCallback
source/VideoPlayerState.hx:43: characters 10-19 : hxcodec.flixel._FlxVideo.VideoHandler has no field playVideo

**Comment by riconuts** [comment]
use hxcodec 2.6.1

**Comment by LuckierCatt** [comment]
its already set to that

**Comment by LuckierCatt** [comment]
nvm I got it working I didn't install a library right
