### ISSUE TITLE
no sex

### ISSUE THREAD

**Issue by nebulazorua** [riconuts/troll-engine#23]
### Describe your bug here.

theres no sex add sex please

### Command Prompt/Terminal logs (if existing)

```bash
error: no sex
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by nebulazorua** [comment]
wait i work on the engine

**Comment by riconuts** [comment]
it's part of working on the engine
