### ISSUE TITLE
what version of the engine does tgt v4 run on? 

### ISSUE THREAD

**Issue by JonnycatMeow** [riconuts/troll-engine#24]
### What is your question?

i was wondering on this

**Comment by riconuts** [comment]
If I remember correctly v4 runs on the first version you can see on the releases page (v0.1). 
We didn't do an engine release for TGT v4.1 though

**Comment by JonnycatMeow** [comment]
ohhh ok thank you

**Comment by nebulazorua** [comment]
V4 uses the original 0.1 version, yes
V4.5 (the halloween update) uses beta6

**Comment by JonnycatMeow** [comment]
oohh
