### ISSUE TITLE
review organization branch

### ISSUE THREAD

**Issue by nebulazorua** [riconuts/troll-engine#26]
### IDK TYPE HERE!!!

it doesnt compile yet but is the organization good??
I have plans to split the fnf menus into its own funkin/ folder so you can use a raw version of the engine w/out any menus or whatever so you can write your own
maybe we can try to make it so the funkin/ folder wont compile when compiling for TGT and vice versa???

(maybe TGT should be split into its own repo???)

**Comment by riconuts** [comment]
> (maybe TGT should be split into its own repo???)

Definitely yes, cause I shouldn't be working on TGT anymore LOL. I didn't immediately do it cause the code was still really dependent on TGT stuff however (I think) that's not the case anymore. It would also save a lot of storage for whoever is interested in the engine but not the TGT mod stuff so yeah

**Comment by nebulazorua** [comment]
> > (maybe TGT should be split into its own repo???)
> 
> Definitely yes, cause I shouldn't be working on TGT anymore LOL. I didn't immediately do it cause the code was still really dependent on TGT stuff however (I think) that's not the case anymore. It would also save a lot of storage for whoever is interested in the engine but not the TGT mod stuff so yeah
> 
> About the organization I have nothing to say because having more than 2 layers of nested folders is something I always hated on other engines :S

fair enough, I can probably cut down on it
I just think it'd be beneficial to put things into folders instead of having it all dumped straight into source

**Comment by nebulazorua** [comment]
Made some changes, mind giving it another look? Now the only nested folders are stuff that were already in folders

**Comment by riconuts** [comment]
> Made some changes, mind giving it another look? Now the only nested folders are stuff that were already in folders

Okay, now this is awesome

**Comment by riconuts** [comment]
Ok so I moved some stuff around and made it work. It should be ready to be merged now? Unless you wanna change something :shrug:

**Comment by nebulazorua** [comment]
> Ok so I moved some stuff around and made it work. It should be ready to be merged now? Unless you wanna change something

oh never saw this
go ahead and merge

**Comment by nebulazorua** [comment]
didnt mean to reopen oops
