### ISSUE TITLE
help some error i got

### ISSUE THREAD

**Issue by KylaOffical2008** [riconuts/troll-engine#28]
### Describe your bug here.

![Screenshot 2024-05-05 071042](https://github.com/riconuts/troll-engine/assets/166725663/e3b1b942-2cad-4866-b6ae-3c3459f91eda)
hhellppp when i just wanna start compiling it's said that \
source/flixel/addons/transition/FlxTransitionableState.hx:55: lines 55-64 : Warning : switchTo is deprecated, use startOutro
source/scripts/FunkinHScript.hx:657: lines 657-674 : Warning : switchTo is deprecated, use startOutro
source/Main.hx:48: characters 42-70 : Uncaught exception process_run
C:\HaxeToolkit\haxe\std/eval/_std/sys/io/Process.hx:1: character 1 : Called from here
source/Github.hx:100: characters 17-84 : Called from here
source/Main.hx:48: characters 42-70 : Called from here

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no i just start 2 compiling and then that happen ToT

**Comment by riconuts** [comment]
Do you have Git installed? Can you run the ```git``` command through cmd?

**Comment by KylaOffical2008** [comment]
i already have it git

**Comment by KylaOffical2008** [comment]
![image](https://github.com/riconuts/troll-engine/assets/166725663/7c6b7cab-d1b9-40f8-8f80-1dbde10be572)
i have git but if i type git in command it's said 
![image](https://github.com/riconuts/troll-engine/assets/166725663/d23dbd31-0730-48cb-96bf-721c49c38b48)

**Comment by riconuts** [comment]
well yeah you might want to fix that, alternatively go to Github.hx on line 99 and change that ```#if !display``` to ```#if false```

**Comment by KylaOffical2008** [comment]
:(((
