### ISSUE TITLE
enum abstract issue when compiling

### ISSUE THREAD

**Issue by juney2008** [riconuts/troll-engine#32]
### Describe your problem here.

So I was trying to compile the Troll Engine to mess around with but I kept on getting this error when building it.

I wasn't sure what I was doing wrong since I was following the instructions and made sure everything was up to date.

![image](https://github.com/riconuts/troll-engine/assets/60835472/fafbc009-67ee-4d9e-8b61-8abc025c3185)

error log from image:
```
source/flixel/FlxObject.hx:1518: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:213: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/Github.hx:78: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/JudgmentManager.hx:10: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/JudgmentManager.hx:40: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/Note.hx:24: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/flixel/addons/transition/FlxTransitionableState.hx:56: lines 56-66 : Warning : switchTo is deprecated, use startOutro
source/scripts/FunkinHScript.hx:664: lines 664-681 : Warning : switchTo is deprecated, use startOutro
source/modchart/Modifier.hx:16: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/flixel/sound/FlxSound.hx:653: characters 18-26 : openfl.media.SoundChannel has no field __source
```

### Are you modding a build from source or with scripts?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No since I wasn't gonna use it to modify the engine for right now.

**Comment by riconuts** [comment]
You don't have to keep everything up to date, the code kinda depends on outdated haxelibs and I haven't tested to see if it works on newer versions of Haxe, which might be the reason you're getting those deprecation warnings. Make sure you're using Haxe 4.2.5 and ran the install_haxelibs bat file that's in the setup folder as that will install the right versions of every library

**Comment by juney2008** [comment]
Ok, I downgraded to 4.2.5 and used the install_haxelib bat file but it gived me a another error.
![image](https://github.com/riconuts/troll-engine/assets/60835472/309011c5-8b5e-4fb8-bb1c-98031f717be9)

**Comment by riconuts** [comment]
mb i forgot something in the bat file, just run `haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit` on cmd or remove LUA_ALLOWED from the Project file if you don't care about it

**Comment by juney2008** [comment]
Ok so adding in linc_luajit worked but now i'm having a issue for the switchTo and the MSVC.
I also would like to apologize for keeping this problem up for longer since I'm not good at compiling before and I do apologize for the silence and late responses too.
![image](https://github.com/riconuts/troll-engine/assets/60835472/cd19df22-aaf8-4bb0-8858-2fd1c3e866eb)

**Comment by juney2008** [comment]
I haven't personally tried compiling other fnf engines since I usely use the actions tab to download beta versions of some fnf engines so not at all. So you can close this now as unsolved. I'm sorry if this was confusing.

**Comment by nebulazorua** [comment]
Likely need to get visual studio stuff
Try following the compile guide on psych engine and then coming back, if you want help

Alternatively, you can use Beta 6. It's a tad old but there's not much different with scripting beyond some modchart changes
