### ISSUE TITLE
timing text is offset left

### ISSUE THREAD

**Issue by nebulazorua** [riconuts/troll-engine#35]
### Describe your bug here.

the timing text is offset left lol
we gotta fix it!!!!
i have my timing text at 0 offset in the customize HUD but ingame its slightly left

**Comment by nebulazorua** [comment]
honestly could also be the combo and judge are offset right?

**Comment by riconuts** [comment]
the timing text is fine, it's the combo and judges that are wrong for some reason

**Comment by riconuts** [comment]
ok i fixed it 84225c9
