### ISSUE TITLE
the app crashes 

### ISSUE THREAD

**Issue by JonnycatMeow** [riconuts/troll-engine#6]
### Describe your bug here.

i tried to play taste for blood on freeplay and it crashed please help me 

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Mac

### Did you edit anything in this build? If so, mention or summarize your changes.

i replaced the assets and other stuff to play tails  gets trolled

**Comment by JonnycatMeow** [comment]
![Screen Shot 2023-05-14 at 12 50 46 AM](https://github.com/riconuts/troll-engine/assets/107599365/60b3153f-c57a-4ece-acde-a6e3cc302777)

**Comment by nebulazorua** [comment]
The mod is made for windows, so anything other than that will likely crash. Sorry
