### ISSUE TITLE
FlxPath Not Found

### ISSUE THREAD

**Issue by Knuxy03** [riconuts/troll-engine#7]
### Describe your problem here.

source/flixel/FlxObject.hx:8: characters 8-27 : Type not found : flixel.path.FlxPath
source/flixel/FlxObject.hx:783: characters 32-39 : Type not found : FlxPath

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope.

**Comment by riconuts** [comment]
Make sure you're using Flixel 5.2.2
