### ISSUE TITLE
Builds for other operating systems

### ISSUE THREAD

**Issue by Stilic** [riconuts/troll-engine#8]
### What feature do you want to get added on the **base** engine?

Hello!
Can it be possible to get precompiled builds for other OSes such as Mac and Linux for the future releases of the engine?

**Comment by nebulazorua** [comment]
If you can get stuff working and do a PR i'll gladly merge it

**Comment by RUvlad1** [comment]
> unlikely, as neither me, rico or echo have a mac or linux machine (and afaik you need one to compile for those systems)
> 
> Linux isnt a big deal because of its open source nature etc, but Mac is an issue

I recently hackintoshed my PC so I can test the macOS build

**Comment by RUvlad1** [comment]
> I recently hackintoshed my PC so I can test the macOS build

update nevermind im reinstalling windows god macOS sucks

**Comment by riconuts** [comment]
epic fail

**Comment by JonnycatMeow** [comment]
i have a mac

**Comment by crowplexus** [comment]
and I have a linux
